version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    groups:
      astro:
        patterns:
          - 'astro'
          - '@astrojs/*'
          - 'astro-*'
      tooling:
        patterns:
          - 'eslint'
          - 'eslint-*'
          - '@typescript-eslint/*'
          - 'typescript-eslint'
          - 'prettier'
          - 'prettier-*'
          - '@ianvs/prettier-plugin-*'
          - 'typescript'
      styling:
        patterns:
          - 'tailwindcss'
          - '@tailwindcss/*'
      runtime:
        patterns:
          - 'github-slugger'
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: chore
      include: scope
